## Lecture01
변수 정의, integers

In [1]:
a = 1

In [2]:
print(type(a))

<class 'int'>


In [3]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


In [4]:
a = 1; b = 2; 

In [5]:
print(a)
print(b)

1
2


### float
부동소수점 --> int와 다르게 소수점을 내포하고 있다.

In [6]:
c = float(a)

In [7]:
print(c)
print(type(c))

1.0
<class 'float'>


In [8]:
int(c)

1

In [9]:
d = 1.1;print(type(d));print(int(d));float(int(d))

<class 'float'>
1


1.0

In [10]:
a = '123'
type(a)

str

In [11]:
a = 'abc'

## list
list를 비롯한 순서가 있는 자료형을 indexing할 때 0부터 시작하며, 마지막은 -1로 한다.

In [12]:
a[1]

'b'

In [13]:
a[0]

'a'

In [14]:
a[-1]

'c'

In [15]:
a = [1, 2, 3]

In [16]:
type(a)

list

In [17]:
a = [1, 2, 'a', [4, 5]]

a 안에 있는 [4,5]를 접근하려면 어떻게 해야 할까?

In [18]:
a[-1]

[4, 5]

In [19]:
a[-1][-1]

5

## string
문자열 --> 길이에 상관없이 string(C랑 다르게 1개도 char이 아니라 string임)

''나 "" 안에 있는 것들!

In [20]:
a = 'abc'; a = list(a)

In [21]:
a

['a', 'b', 'c']

In [22]:
b = ''

In [23]:
for letter in a:
    b += letter

In [24]:
b

'abc'

In [25]:
type((1,2))

tuple

In [26]:
a = (1,2,3)

In [27]:
a[1] = 3

TypeError: 'tuple' object does not support item assignment

## Dictionary
{} 안에 key:value로 들어가 있는 형태를 dictionary라고 한다!

In [28]:
a = {"a" : "apple", "b" : 'banana', 'n' : 2019}

In [29]:
# dictionary는 []안에 key 값을 넣어서 자료에 접근을 한다.

print(type(a))
print(a["a"])

<class 'dict'>
apple


key, value 없는 대괄호는 set으로, 중복된 값을 없앤다.

In [30]:
c = {1,1,1,1,1,2,3}

In [31]:
type(c)

set

dictionary 또한 길이를 가진다!

In [32]:
len(c)

3

In [33]:
a= [(1,2,3), (4,5,6)]
print(type(a))
print(f'first element of a is {a[0]}\n')
print(f'first element\'s type is {type(a[0])}')

<class 'list'>
first element of a is (1, 2, 3)

first element's type is <class 'tuple'>


## import numpy as np
harddisk에 있는 numpy package를 메모리에 올려놓는 것!(없으면 package manager로 깔아줘야 함 --> pip/conda)

행렬연산을 위해서는 행렬 연사용 package인 numpy를 사용해줘야 한다!

In [34]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))
print(b.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


numpy.array --> numpy에서 제공하는 행렬곱용 array datatype으로 생각하기!

In [35]:
# indexing numpy array : row --> column
print(b[0])
print(b[0][1])

[1 2 3]
2


In [36]:
# * --> array의 element별로 곱을 해줌!
# 사실 np.array는 완전히 행렬이라고는 할 수 없음!
print(b*b)

[[ 1  4  9]
 [16 25 36]]


In [37]:
c = np.matrix(b)
print(type(c))

<class 'numpy.matrixlib.defmatrix.matrix'>


In [38]:
c

matrix([[1, 2, 3],
        [4, 5, 6]])

In [39]:
# matrix를 *로 곱해주려면 shape를 맞춰줘야 한다!
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [40]:
# 곱을 위해 transpose로 shape를 맞춰줘야 함!
# np.matmul로 곱해주기도 함!
print(c * c.T)
print(np.matmul(c,c.T))

[[14 32]
 [32 77]]
[[14 32]
 [32 77]]


## Class??
OOP(object oriented programming) --> class - object(형상 - 실체)

특정 함수/변수 : 같이 다니는 경우 빈번 --> class로 묶어줌! --> 사용하기 매우 편리함!

우리는 그냥 만들어진 class를 사용하면 됨쓰!

In [41]:
l = ['a','b','c']

In [42]:
print(type(l))

<class 'list'>


In [43]:
l.append('d')

In [44]:
print(l)

['a', 'b', 'c', 'd']
